### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by JustONOFF** [Igor55x/UAAE#1]
I don't know if I did this right, I just tried to build this program with VS. I opened the project map and started the debugging, but when i started UAAE I got an error message, saying the classdata.tpk file is missing. I copied a classdata file  from the UABE and the program started. The next problem was that when I wanted to import a .assets file, I got a second error message. It said something about 'Object reference not set to an instance of an object.' What did I do wrong and is it possible to get an instruction to build this properly, because I couldn't find any instructions how to do that

**Comment by Igor55x** [comment]
**You did the right thing by building the program with Visual Studio.**
I recommend that you use this updated [classdata.tpk](https://github.com/DerPopo/UABE/files/6221297/classdata.zip) file.
I tested the "Import" option and it works fine with all the files I tested.
### Can you please send me the file so I can test it?

**Comment by JustONOFF** [comment]
I did like you said and replaced classdata.tpk with the one you provided and sadly it's still not working :/
Here's my .assets file, let's see if you are able to open it:
[sharedassets0.zip](https://github.com/Igor55x/UAAE/files/6528848/sharedassets0.zip)

**Comment by Igor55x** [comment]
> I did like you said and replaced classdata.tpk with the one you provided and sadly it's still not working :/
> Here's my .assets file, let's see if you are able to open it:
> [sharedassets0.zip](https://github.com/Igor55x/UAAE/files/6528848/sharedassets0.zip)

It seems that the unity version of this assets file is not supported even by the updated `classdata.tpk` file.
Unity version of this file: **2020.3.9f1**.
Unity version supported by the `classdata.tpk` file: **2020.2.***.
I'll try to do something about it.

**Comment by Igor55x** [comment]
Done.
