### ISSUE TITLE
Support newer versions of Unity

### ISSUE THREAD

**Issue by treetopdevs** [Igor55x/UAAE#10]
This doesn’t work with Unity version 2020.3.7 or newer. How difficult is it to update this to work with this or newer versions?

**Comment by Igor55x** [comment]
> How difficult is it to update this to work with this or newer versions?

This is quite complicated because you have to create the cldb file manually (**one for each version**), which takes a lot of time.

**Comment by Igor55x** [comment]
Here is the [`classdata.tpk`](https://github.com/Igor55x/UAAE/files/6682191/classdata.zip) file that supports unity versions up to **2020.3.***.
