### ISSUE TITLE
Where can I get the TypeName and TypeID of Unity Assets?

### ISSUE THREAD

**Issue by mskgroup** [Igor55x/UAAE#11]
I mean if I want to make a new version of Unity's Database, where can I get these two items?

**Comment by Igor55x** [comment]
> I mean if I want to make a new version of Unity's Database, where can I get these two items?

**1.** You need to download the **[TypeTreeDumper](https://github.com/DaZombieKiller/TypeTreeDumper)** (unstable) tool
**2.** You need to install the version of Unity that you need to create the new database
**3.** You need to change this [line](https://github.com/DaZombieKiller/TypeTreeDumper/blob/master/TypeTreeDumper.Bootstrapper/Program.cs#L17) to the path to Unity.exe. Now you can build the program and run `TypeTreeDumper.Bootstrapper.exe`

**Comment by mskgroup** [comment]
thank you very much!

**Comment by Igor55x** [comment]
> thank you very much!

Try this [build](https://github.com/Igor55x/UAAE/files/6685914/TTD-Build.zip) instead.
