### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [Igor55x/UAAE#12]
Hello, how do I install this tool to be able to use it?

**Comment by Igor55x** [comment]
You don't need to install this tool.
**All you need to do is install Visual Studio 2019 and [build](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?view=vs-2019#build-the-solution) the project.**

**Comment by mskgroup** [comment]
I will build the new version as quickly as possible to facilitate people who do not use VS

https://github.com/mskgroup/Unity-Game-localization-tutorial-and-toolkit

UAAE in Tools/UAAE_BuilsDate.zip
