### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by Rydyc** [Igor55x/UAAE#14]
Hello, thank you very much for the UAAE tool!

When unpacking the bundle file of Among Us, then in the .resS files it says that it is not compatible with the versión :/

**Comment by Igor55x** [comment]
> When unpacking the bundle file of Among Us, then in the .resS files it says that it is not compatible with the versión :/

Are you using the mobile version of Among Us?
If so, please send me this bundle file.

**Comment by Rydyc** [comment]
> > When unpacking the bundle file of Among Us, then in the .resS files it says that it is not compatible with the versión :/
> 
> I think you are using the mobile version of **Among Us**. Right?
> If so, please send me this bundle file.

Thanks for answering!
it's the pc version:
https://www.mediafire.com/file/1p5ubn3pzci7rk6/initialmaps_assets_all_607d8d709332624f1a67a63abf9c38a8.bundle/file

**Comment by Rydyc** [comment]
Have you been able to fix the error? :/

**Comment by Igor55x** [comment]
> Have you been able to fix the error? :/

Sorry, but I can't fix this.
