### ISSUE TITLE
how do i build

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [Igor55x/UAAE#16]
there is nothing that tells me how to build

**Comment by Igor55x** [comment]
> there is nothing that tells me how to build

If you need latest build (newer, but unstable): **Install Visual Studio 2019 and [build](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?view=vs-2019#build-tlhe-solution) the source project.**
Or latest release (older and missing bug fixes): [link](https://github.com/Igor55x/UAAE/releases).

**Comment by imadeagithubaccountforthis** [comment]
bruh that's not telling me ANYTHING like HOW TO BUILD IT. HOW i said HOW not what to use HOW

**Comment by imadeagithubaccountforthis** [comment]
OPEN THIS RIGHT BACK UP SINCE WE AREN'T DONE HERE

**Comment by Igor55x** [comment]
> OPEN THIS RIGHT BACK UP SINCE WE AREN'T DONE HERE

See README.MD
