### ISSUE TITLE
Editing textures issue [TexToolWrap.dll]

### ISSUE THREAD

**Issue by TheOnlineLime** [Igor55x/UAAE#17]
So I'm trying to change assets for a game called Getting Over It on version 2020.3.6f1.
Every time I try and edit the texture it spits out an error about the TexToolWrap.dll file.

I only use UABE for replacing models/textures so this is very important.

**Comment by Igor55x** [comment]
> Every time I try and edit the texture it spits out an error about the TexToolWrap.dll file.

Are you using the latest release?
If so, send me the file of this game.
