### ISSUE TITLE
i cant open a .emip file

### ISSUE THREAD

**Issue by KissesKloset** [Igor55x/UAAE#20]
when i click "load package file" it crashes and when i press open it does nothing

**Comment by Igor55x** [comment]
> when i click "load package file" it crashes and when i press open it does nothing

**Do you mean the bundle file?**
If so, please send me the bundle file.
But if you mean the `.emip` file, then this feature is not supported at the moment.

**Comment by Igor55x** [comment]
Idk how to help you, so I'm closing this issue.
