### ISSUE TITLE
Failed to decode texture(ETC2_RGBA8Crunched)

### ISSUE THREAD

**Issue by TheCookiss** [Igor55x/UAAE#24]
![Снимок](https://user-images.githubusercontent.com/88102619/127356081-9a7f6cc5-8254-4242-8147-2866046dd16e.PNG)
Hello everyone, I ran into this problem: I needed to replace textures in the game to create a mod, but when I did export to PNG, I got such an error. Please help me how to fix this?

**Comment by Igor55x** [comment]
This texture format is not supported yet. But I'll add support soon.

**Comment by TheCookiss** [comment]
> 
> 
> This texture format is not supported yet. But I'll add support soon.

Thank you so much in advance. Let me know when you will

**Comment by TheCookiss** [comment]
> 
> 
> This texture format is not supported yet. But I'll add support soon.

Thank you so much in advance. Let me know when you will

**Comment by Igor55x** [comment]
> Thank you so much in advance. Let me know when you will

Done.

**Comment by TheCookiss** [comment]
> 
> 
> > Thank you so much in advance. Let me know when you will
> 
> Done. Now you can try it by downloading a [**nightly build**](https://nightly.link/Igor55x/UAAE/workflows/dotnet-desktop/master/UAAE-Windows.zip).

TYSM
