### ISSUE TITLE
Saving and overwriting 1GB assets takes over an hour

### ISSUE THREAD

**Issue by drongood12** [Igor55x/UAAE#3]
If you change and try to save the assets file, regardless of whether you are overwriting or saving to a new file, the program records for about an hour.

**Comment by Igor55x** [comment]
What version of unity is the game?
And if you can please send me the file.

**Comment by drongood12** [comment]
2019.4.22f i guess
https://wiki.facepunch.com/rust/Creating-a-server after executing quick install, the file will be in Bundles/shared/content.bundle

**Comment by Igor55x** [comment]
[UAAE-rel1-win.zip](https://github.com/Igor55x/UAAE/files/6566838/UAAE-rel1-win.zip)
