### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SakiMika** [Igor55x/UAAE#30]
Hello, I tried your tool, but it crashes on startup. How to fix this?
Full error log
Faulting application name: AssetsAdvancedEditor.exe, version: 1.0.0.0, time stamp: 0x609308e7
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1474, time stamp: 0x5ae7af90
Exception code: 0xe0434352
Fault offset: 0x0000000000043b19
Faulting process id: 0x35f4
Faulting application start time: 0x01d7886905672d70
Faulting application path: C:\Users\Admin\Desktop\UAAE\AssetsAdvancedEditor.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dc02f0bf-7254-4f62-b827-daa47d73defb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Igor55x** [comment]
I can't fix the issue because I need `stack trace`, not the .net runtime error: [example](https://github.com/Igor55x/UAAE/files/6925129/error.txt).

**Comment by SakiMika** [comment]
> I can't fix the issue because I need `stack trace`: [example](https://github.com/Igor55x/UAAE/files/6925129/error.txt).

Nevermind, I found the solution and now it work
