### ISSUE TITLE
Does not appear to load any file

### ISSUE THREAD

**Issue by xtremeqg** [Igor55x/UAAE#33]
Tried this tool on the resources.assets file of Dyson Sphere Program. Unity version 2018.4.12f1_59ddc4c59b4f. I let it sit and run for about 5 minutes at which point it ate all 4 gigs of my virtual machine. I also tried other files (sharedassets0.*) but was told the file was invalid / wrong version.

I opened the same file with UABE and all 28640 entries were loaded in about a minute, displaying a progress indicator while only using 50 megs of memory. UABE was also able to open the other files that UAAE said were invalid / wrong version.

**Comment by Igor55x** [comment]
Can you send me one of the files?

**Comment by Igor55x** [comment]
Can you send me one of the files?

**Comment by xtremeqg** [comment]
Somewhat difficult considering the files are copyrighted and fairly large (>1 gig). You should be able to obtain a copy of the game files from Steam or "alternative" sites (version 0.8.20.7996).

My intent was to lower the size of texture assets as this particular game does not care about available VRAM and just takes it all and them some. On my system this happens to result in sub-10 FPS at even tiny screen sizes. With the help of UABE however I found that except for the icons, all textures are most likely either procedurally generated or pixel shaders. I did find some stupidly large normal maps (2048x2048) but they look stock and not worth downsizing and will not solve the problem. Maybe I'm missing something as I'm not that familiar with Unity. There was this really large "Text" resource however...

I was able to work around my original problem with BepInEx + MoreGraphicsOptions plugin. Game looks like crap but my FPS doubled. I know that won't help you figure out why UAAE went off to cure cancer but its something.

**Comment by xtremeqg** [comment]
> Try this [build](https://github.com/Igor55x/UAAE/files/7068012/UAAE-fix33.zip). I hope it works faster now.

Sorry I was unable to test sooner. The attached fixed version no longer consumes all system memory and loaded the same file just a few seconds. Thank you for your efforts.
