### ISSUE TITLE
doesnt show the full files contents (latest build)

### ISSUE THREAD

**Issue by LoganPlayzUsezGitHub** [Igor55x/UAAE#34]
i was editing among us files when i loaded sharedassets7.assets it only showed one chunk but every other asset didnt have missing chunks

help im confused

**Comment by LoganPlayzUsezGitHub** [comment]
here is a image
![image](https://user-images.githubusercontent.com/64603591/131229494-f14de195-2e79-491c-9330-20c80b9be48d.png)

**Comment by Igor55x** [comment]
> ... it only showed one chunk but every other asset didnt have missing chunks

What do you mean?
I opened this file and everything loads correctly.
I need a little bit more info to solve this issue.

**Comment by Igor55x** [comment]
I'm closing this because everything works correctly.
