### ISSUE TITLE
System.Overflow.Exception

### ISSUE THREAD

**Issue by ZedhunterJR** [Igor55x/UAAE#36]
![Screenshot 2021-08-30 232100](https://user-images.githubusercontent.com/89736834/131371457-253870d8-61d4-455a-83d8-f3c34bd3eee4.png)
When I try to decompress the file, this happens. Any idea how to fix this?
[5037_zuka_battle_raw_h.zip](https://github.com/Igor55x/UAAE/files/7078046/5037_zuka_battle_raw_h.zip)

**Comment by Igor55x** [comment]
The exception is thrown on this line:
![Problem line](https://user-images.githubusercontent.com/74247502/131519977-e3eef643-c1d0-4f4a-9f4a-add8d7af5f15.png)

The `directoryCount` variable takes a negative value, which is why an exception occurs.
This happens with bundles whose version is `2019.4.15f1`
**This means that the bundle has a new format which unfortunately I don't know.**

**Comment by ZedhunterJR** [comment]
> The exception is thrown on this line:
> ![Problem line](https://user-images.githubusercontent.com/74247502/131519977-e3eef643-c1d0-4f4a-9f4a-add8d7af5f15.png)
> 
> The `directoryCount` variable takes a negative value, which is why an exception occurs.
> This happens with bundles whose version is `2019.4.15f1`
> **This means that the bundle has a new format which unfortunately I don't know.**

Well okay then. Thanks for the reply anyway.

**Comment by Igor55x** [comment]
After some tests I was able to find out that the bundle header of this unity version are **encrypted** or **compressed**.
I know it doesn't help but it's better than nothing.

**Comment by ZedhunterJR** [comment]
Pay me no mind if you think I'm asking unrelated questions. Is there a traditional way to open an .assetbundle file in unity, or the file format is just made so that it's very difficult to get access to?

**Comment by kourain** [comment]
liệu bạn có thể thêm 2019.4.15f1 không
trò chơi của tôi sử dụng phiên bản này

**Comment by kourain** [comment]
can you add 2019.4.15f1
my game uses this version

**Comment by Igor55x** [comment]
> can you add 2019.4.15f1

Sorry, but I can't atm, because I don't know the format of the bundle.

**Comment by Igor55x** [comment]
> ... Is there a traditional way to open an .assetbundle file in unity ...

No, unity will not open the `.assetbundle`, because it's not a source file.

> ... the file format is just made so that it's very difficult to get access to?

This is most likely true, but maybe it's just a new format in which the `bundle header` is compressed.

**Comment by kourain** [comment]
I have a file that can be opened with UABE Avalonia
[157.zip](https://github.com/Igor55x/UAAE/files/7126703/157.zip)
but when compressing the file back into the game, the game doesn't recognize it.

And here is the file I created from Unity 2019.4.15f1.
[157_buzhihuowu_battle_base_low.zip](https://github.com/Igor55x/UAAE/files/7126715/157_buzhihuowu_battle_base_low.zip)

**Comment by Igor55x** [comment]
> but when compressing the file back into the game, the game doesn't recognize it.

Try just saving the bundle without any compression.
