### ISSUE TITLE
Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by rezamms** [Igor55x/UAAE#37]
![Twelve Minutes](https://i.imgur.com/RDibVDG.png)
When I try to open an assets file from **Twelve Minutes** this happened.

**Comment by Igor55x** [comment]
> https://i.imgur.com/RDibVDG.png
> when i try to open a asset from Twelve Minutes this happend

**Are you using the [latest build](https://nightly.link/Igor55x/UAAE/workflows/dotnet-desktop/master/UAAE-Windows.zip)?**
That's because I have the same issues: #23, #19

**Comment by rezamms** [comment]
OH. Yeah it's fixed
