### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cacarasa** [Igor55x/UAAE#4]
thanks for your work! but the software dont work wit unity 2020....I can't edit anything

![Sin título1](https://user-images.githubusercontent.com/20714192/120806568-6722f600-c51d-11eb-83c4-976140aa9ac4.png)

thanks in advance

**Comment by Igor55x** [comment]
> ....I can't edit anything

What does that mean?
**You can't edit the asset or the `assets` file won't open?**
I need a little more information so I can fix it.

**Comment by cacarasa** [comment]
dont open... look the file if you want:
here is the file with texts:
[https://www32.zippyshare.com/v/c51Gacwn/file.html](url)

thanks in advance

**Comment by Igor55x** [comment]
**I think you downloaded the [first release](https://github.com/Igor55x/UAAE/releases/download/v1/UAAE-rel1-win.zip), but it does not work with this and many other files.**
So download the [latest source code](https://github.com/Igor55x/UAAE/archive/refs/heads/master.zip) and build the program yourself.
