### ISSUE TITLE
Edit mesh

### ISSUE THREAD

**Issue by luccaxPRO** [Igor55x/UAAE#43]
Hi, how is it possible to edit mesh? Tried importing raw and dump, but mesh is invisible in game...

**Comment by Igor55x** [comment]
> Hi, how is it possible to edit mesh? Tried importing raw and dump, but mesh is invisible in game...

At the moment it is not possible as this option is not implemented.
But I plan to implement it in the near future.

**Comment by luccaxPRO** [comment]
try to implement please... I make mods for a game, and it updated to unity version 2019.4.31, and I'm no longer able to edit the 3d :(

**Comment by Igor55x** [comment]
Which mesh format is preferred?
