### ISSUE TITLE
This update from yesterday, is it support 3d mesh editing?

### ISSUE THREAD

**Issue by luccaxPRO** [Igor55x/UAAE#46]
This update from yesterday, is it support 3d mesh editing?

**Comment by Igor55x** [comment]
> This update from yesterday, is it support 3d mesh editing?

**No, it's just a few bug fixes in the program.**
An update with mesh support will be called "mesh support (wip)" or sth like that.

**Comment by luccaxPRO** [comment]
wow, I'm looking forward to this update, thanks for your attention and sorry for the inconvenience! @Igor55x
