### ISSUE TITLE
Error when save

### ISSUE THREAD

**Issue by jemjom933** [Igor55x/UAAE#48]
software works great, i can export and import, but can't save, it gives error
unity 2020.3.16f1

<a href="https://imgbb.com/"><img src="https://i.ibb.co/HtwDfZR/error.png" alt="error" border="0"></a>

**Comment by Igor55x** [comment]
Are you using the latest release?
You need to give me a bit more info about the problem if you want help:
**Stack trace** or **file** so I can test it.
