### ISSUE TITLE
Unable to import dumped Monobehaviour with an enum

### ISSUE THREAD

**Issue by mskgroup** [Igor55x/UAAE#6]
Unable to import dumped Monobehaviour with an enum

![屏幕截图 2021-06-06 164937](https://user-images.githubusercontent.com/51709279/121109364-fee65400-c83d-11eb-9b2d-a4e9c2ca8937.png)

**Comment by Igor55x** [comment]
> Unable to import dumped Monobehaviour with an enum

Can you send me the file so I can figure out what went wrong?

**Comment by mskgroup** [comment]
game download：https://ifscl.b-cdn.net/standalone/IFSCL_41X_Setup.exe

The following is an example file:
[TextColor_highlight-sharedassets0.assets-43.txt](https://github.com/Igor55x/UAAE/files/6616909/TextColor_highlight-sharedassets0.assets-43.txt)
[Gunship.IFSCL.SDF.Material-sharedassets0.assets-7.txt](https://github.com/Igor55x/UAAE/files/6616910/Gunship.IFSCL.SDF.Material-sharedassets0.assets-7.txt)
[LiberationSans.SDF-sharedassets0.assets-41.txt](https://github.com/Igor55x/UAAE/files/6616911/LiberationSans.SDF-sharedassets0.assets-41.txt)
