### ISSUE TITLE
Missing resS Issue

### ISSUE THREAD

**Issue by ArgoreOfficial** [Igor55x/UAAE#60]
I tried decompressing a .bundle file, went well, got the .asset and all. Then when i tried to export a PNG i get this error

![image](https://user-images.githubusercontent.com/45431685/152663506-011fac5f-595a-4e50-a8e1-77e801193a64.png)

Is this file format not supported or am I missing something?

**Comment by Igor55x** [comment]
This error occurred because `fileInst.parentBundle` had the value `null`.
Fixed in a76a898.
