### ISSUE TITLE
Plugins are not showing up

### ISSUE THREAD

**Issue by Marsi84** [Igor55x/UAAE#63]
I am trying to export a TextAssets but there is no plugin showing up.
Am I doing something wrong here? I am using UAAE V1.0

![image](https://user-images.githubusercontent.com/15144363/154797995-d0b0ceb0-4789-4214-be51-7b79b1824717.png)

I also tried with UAAE V1.2, the result is the same except that the "Execute plugin" button is not showing up.

![image](https://user-images.githubusercontent.com/15144363/154798083-995e9bfc-f91c-4257-856f-0909df0ac2e1.png)

**Comment by Igor55x** [comment]
Use the latest build, it should work.
