### ISSUE TITLE
How Do You Even OPEN This?!

### ISSUE THREAD

**Issue by WilliytheGamerDude** [Igor55x/UAAE#68]
Every time I go to open this, it gives me an error message saying "To run this application, you must install missing frameworks for .NET." But the problem is that I already have the latest .NET installed. I've installed both x86 and x64, and my Windows OS doesn't support Arm64 (but I doubt that matters). So what the f*** is going on?!

**Comment by woctezuma** [comment]
- https://github.com/nesrak1/UABEA/issues/153
