### ISSUE TITLE
Unable to read the file

### ISSUE THREAD

**Issue by slayer6409** [Igor55x/UAAE#69]
When trying to open a resources.assets or any other asset file, I get an error saying 
"Unable to read the file!
Invalid file or unknown (unsupported) version"

The unity version of the asset files are 2020.3.25f1

The game that I am trying to open is Phasmophobia. 

Am I doing something wrong?

**Comment by woctezuma** [comment]
Try another tool to see if there is an issue with the file:
- https://github.com/DerPopo/UABE/issues/465

**Comment by slayer6409** [comment]
I was able to open it with UABEA and asset studio just not with this one or UABE.
