### ISSUE TITLE
UAAE_Alteritive

### ISSUE THREAD

**Issue by AkagiVoid** [Igor55x/UAAE#73]
Judging by this developer's absents of one yr he either got bad sick, abandon this tool, or dead. XwX

So here is an UAAE alteritive dat operates very similar to how this tool functions and its mar up to date than this tool. ^w^
Link: [UABEA](https://github.com/nesrak1/UABEA) by nesrak1. ^w^

**Comment by Igor55x** [comment]
I'm sorry, but I don't want to continue working on UAAE anymore.
Use alternatives such as [UABEA](https://github.com/nesrak1/UABEA) and [UABE](https://github.com/SeriousCache/UABE).

**Comment by Igor55x** [comment]
Sorry, but I don't want to continue working on UAAE anymore (I might change my mind, but it's unlikely).
I don't have that much time to continue development.
Use alternatives such as [UABEA](https://github.com/nesrak1/UABEA) and [UABE](https://github.com/SeriousCache/UABE).
