### ISSUE TITLE
FBX SUPPORT

### ISSUE THREAD

**Issue by Minileandro** [Igor55x/UAAE#9]
Could add the feature to extract 3D models in fbx?
In which everything included in it comes (eg vertex color, uv)

**Comment by Igor55x** [comment]
Yes, I can. But you'll have to wait until I make the Texture plugin.

**Comment by Minileandro** [comment]
So it could take a while, right?

**Comment by Igor55x** [comment]
> So it could take a while, right?

Yes, it is. I can't just quit working on the Texture plugin and work on the Fbx plugin.
